# Generated by Django 4.0.4 on 2022-05-28 05:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='request_s',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wilaya', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=100)),
                ('taken', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='date_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)])),
                ('date', models.TimeField(blank=True, null=True)),
                ('debah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debah', to='debah.deba7')),
                ('organisation', models.ForeignKey(limit_choices_to={'is_org': True}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to=settings.AUTH_USER_MODEL)),
                ('simple_user', models.ForeignKey(limit_choices_to={'is_org': False}, on_delete=django.db.models.deletion.CASCADE, related_name='simple_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
